#!/bin/sh

PROJECT='/path'

files=`find ${PROJECT}/ -type f -name '*.c' -or -name '*.cpp' -or -name '*.h'`
if [ -z "$files" ]; then
	# nothing to do
	exit 0
fi

clean01() {
	astyle \
		--suffix=none \
		--style=allman \
		--formatted -v \
		\
		--indent=force-tab=8 \
		--indent-classes \
		--indent-preproc-define \
		--indent-switches \
		--indent-after-parens \
		--max-instatement-indent=80 \
		--lineend=linux \
		\
		--unpad-paren \
		\
		--pad-oper \
		--pad-comma \
		--pad-header \
		--pad-param-type \
		--attach-return-type-decl \
		\
		--align-pointer=name \
		\
		--break-one-line-headers \
		--keep-one-line-blocks \
		--keep-one-line-statements \
		\
		$files
}

# Remove consecutive Whitespace
clean02() {
	sed 's/( \+/(/g' -i $files
	sed 's/ )\+/)/g' -i $files
	sed 's/Context_t  \+/Context_t /g' -i $files
}

clean03() {
	find ${PROJECT} -type f -exec dos2unix -k -q {} \;
}

clean01
clean02
clean03
